export const testBotDefiniton = {
  _id: "619bc88980f65602fd7081aa",
  chart: {
    nodes: {
      node1: {
        id: "node1",
        title: "Start!",
        user: false,
        preventRemoval: true,
        content:
          "$\ne = mc^2\n$\n\n - [x] List item\n$$\n\\begin{aligned}\\\\T( (v_1 + v_2) \\otimes w) &= T(v_1 \\otimes w) + T(v_2 \\otimes w)\\\\\nT( v \\otimes (w_1 + w_2)) &= T(v \\otimes w_1) + T(v \\otimes w_2) \\\\\nT( (\\alpha v) \\otimes w ) &= T( \\alpha ( v \\otimes w) ) \\\\\nT( v \\otimes (\\alpha w) ) &= T( \\alpha ( v \\otimes w) )\n\n\\end{aligned}\n\n$$\n\n$$\n\nT f = T \\left( \\sum_{k=1}^n \\alpha_k (v_k \\otimes w_k) \\right) = \\sum_{k=1}^n \\alpha_k T (v_k \\otimes w_k)\n\n$$\n\n> So you can give people the **choice** to use a more familiar, discoverable interface.\n\n |   First Header |      Second Header |\n| -------------: | -----------------: |\n| Content Cell 1 |   `Content` Cell 1 |\n| Content Cell 2 | **Content** Cell 2 |<dumbot-boubble/>\n\n # A demo of React\n ${multiOut}   \n\nLift($L$) can be determined by Lift Coefficient ($C_L$) like the following\nequation.\n\n$$\nL = \\frac{1}{2} \\rho v^2 S C_L\n$$\n\nhttp://techslides.com/demos/sample-videos/small.webm\n\nWelcome *your* user with a nice **message**!😂\n  ![alt text](//v2.grommet.io/assets/IMG_4245.jpg \"Markdown Image\")    \n![image.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)<dumbot-boubble/>\nThese features **do not work by default**.\n        \n        \n👆 Use the toggle above to add the plugin.\n\n`react-markdown` is a markdown component for R ${multiOut} eact.\n\n👉 Changes are re-rendered as you type.\n\n👈 Try writing some markdown on the left.\n\n## Overview\n\n* Follows [CommonMark](https://commonmark.org)\n* Optionally follows [GitHub Flavored Markdown](https://github.github.com/gfm/)\n* Renders actual React elements instead of using `dangerouslySetInnerHTML`\n* Lets you define your own components (to render `MyHeading` instead of `h1`)\n* Has a lot of plugins\n\n## Table of contents\n\nHere is an example of a plugin in action\n([`remark-toc`](https://github.com/remarkjs/remark-toc)).\nThis section is replaced by an actual table of contents.\n\n## Syntax highlighting\n\nHere is an example of a plugin to highlight code:\n[`rehype-highlight`](https://github.com/rehypejs/rehype-highlight).\n\n```js showLineNumbers\nimport React from 'react'\nimport ReactDOM from 'react-dom'\nimport ReactMarkdown from 'react-markdown'\nimport rehypeHighlight from 'rehype-highlight'\n\nReactDOM.render(\n  <ReactMarkdown rehypePlugins={[rehypeHighlight]}>{'# Your markdown here'}</ReactMarkdown>,\n  document.querySelector('#content')\n)\n```\n\nPretty neat, eh?\n\n## GitHub flavored markdown (GFM)\n\nFor GFM, you can *also* use a plugin:\n[`remark-gfm`](https://github.com/remarkjs/react-markdown#use).\nIt adds support for GitHub-specific extensions to the language:\ntables, strikethrough, tasklists, and literal URLs.\n\nThese features **do not work by default**.\n👆 Use the toggle above to add the plugin.\n\n| Feature    | Support              |\n| ---------: | :------------------- |\n| CommonMark | 100%                 |\n| GFM        | 100% w/ `remark-gfm` |\n\n~~strikethrough~~\n\n* [ ] task list\n* [x] checked item\n\nhttps://example.com\n\n## HTML in markdown\n\n⚠️ HTML in markdown is quite unsafe, but if you want to support it, you can\nuse [`rehype-raw`](https://github.com/rehypejs/rehype-raw).\nYou should probably combine it with\n[`rehype-sanitize`](https://github.com/rehypejs/rehype-sanitize).\n\n<blockquote>\n  👆 Use the toggle above to add the plugin.\n</blockquote>\n\n## Components\n\nYou can pass components to change things:\n\n```js\nimport React from 'react'\nimport ReactDOM from 'react-dom'\nimport ReactMarkdown from 'react-markdown'\nimport MyFancyRule from './components/my-fancy-rule.js'\n\nReactDOM.render(\n  <ReactMarkdown\n    components={{\n      // Use h2s instead of h1s\n      h1: 'h2',\n      // Use a component instead of hrs\n      hr: ({node, ...props}) => <MyFancyRule {...props} />\n    }}\n  >\n    # Your markdown here\n  </ReactMarkdown>,\n  document.querySelector('#content')\n)\n```\n\n## More info?\n\nMuch more info is available in the\n[readme on GitHub](https://github.com/remarkjs/react-markdown)!\n\n***\n\nA component by [Espen Hovlandsdal](https://espen.codes/)",
        position: { x: 0, y: 0 },
        type: "start",
        output: { type: "null", id: "start" },
        ports: {
          default: {
            id: "default",
            bgColor: "brand",
            text: "default",
            index: 1,
            properties: {},
          },
        },
        size: { h: 369, w: 250 },
      },
      N2XbELZtyn: {
        id: "N2XbELZtyn",
        type: "message",
        user: false,
        content: "Type your message here",
        position: { x: 1473.25, y: 484.25 },
        title: "Message",
        output: { type: "null", id: "message_0_GqAK378P" },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 0,
            properties: {},
          },
        },
        size: { h: 213, w: 250 },
      },
      KfB4u17Hzo: {
        id: "KfB4u17Hzo",
        type: "buttons",
        user: true,
        content: "please pick an option",
        position: { x: 46, y: 419 },
        title: "Buttons",
        output: { id: "multiOut", type: "text" },
        properties: {
          displayAs: "message",
          min: 2,
          max: 4,
          direction: "row",
          label: "buttons",
        },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 1,
            properties: {},
          },
          option1: {
            bgColor: "options",
            id: "option1",
            text: "test port 1",
            index: 2,
            properties: {
              value: "test port 1",
              icon: "Accessibility",
              text: "test port 1",
            },
          },
          option2: {
            bgColor: "options",
            id: "option2",
            text: "testport2 😂",
            index: 3,
            properties: {
              value: "testport2 😂",
              icon: "Achievement",
              text: "testport2 😂",
            },
          },
          option3: {
            bgColor: "options",
            id: "option3",
            text: "Chat with operator",
            index: 4,
            properties: {
              value: "Chat with operator",
              icon: "Accessibility",
              text: "Chat with operator",
            },
          },
          option4: {
            bgColor: "options",
            id: "option4",
            text: "edit me 2",
            index: 5,
            properties: { value: "edit me 2", icon: "", text: "edit me 2" },
          },
          option5: {
            bgColor: "options",
            id: "option5",
            text: "LibraryComponent",
            index: 6,
            properties: {
              value: "LibraryComponent",
              icon: "",
              text: "LibraryComponent",
            },
          },
        },
        size: { h: 364, w: 250 },
      },
      "0Z3bTAzvaE": {
        id: "0Z3bTAzvaE",
        type: "dumbotSnippet",
        user: true,
        content: "Javascript Snippet",
        position: { x: 1157.5, y: 15 },
        title: "User snippet",
        properties: {
          label: "snippet",
          code: 'async function _dumbot_user_snippet(SnippetContext)/* -- readonly -- */ \n  {\n  const callApi = async (label) => {\n    //onCallHost will call a function passed as a property into the bot instance if defined. You can cal an api\n    // from the host and provide data out\n    const data = await SnippetContext.onCallHost(label, SnippetContext.variables);\n    return data;\n  }\n\n  // you can use await \n  const res = await callApi("testlabel");\n  console.log("RESPONSEEEEE", res)\n  // set variables on the Bot\n  SnippetContext.onSetVariable("aaa", res);\n  // read variables from the bot\n  console.log("Available variables",SnippetContext.variables);\n  console.log("Available ports",SnippetContext.ports);\n  // proceed with the flow on port default\n return SnippetContext.ports.exit2;\n}/* -- readonly -- */ ',
        },
        output: { type: "object", id: "dumbotSnippet_wGmwpsb2Ml" },
        silent: true,
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 1,
            properties: {},
          },
          exit1: {
            bgColor: "options",
            id: "exit1",
            text: "exit 1",
            index: 2,
            properties: { value: "exit 1" },
          },
          exit2: {
            bgColor: "options",
            id: "exit2",
            text: "exit 2",
            index: 3,
            properties: { value: "exit 2" },
          },
          exit3: {
            bgColor: "options",
            id: "exit3",
            text: "exit 3",
            index: 4,
            properties: { value: "exit 3" },
          },
        },
        size: { h: 294, w: 250 },
      },
      Xe2ZftbxOG: {
        id: "Xe2ZftbxOG",
        type: "message",
        user: false,
        content:
          "well done    ${cstComponent}!!!!!\n| Head | Head | Head | Head | Head | Head |\n| --- | --- | --- | --- | --- | --- |\n| Data | Data | Data | Data | Data | Data |\n| Data | Data | Data | Data | Data | Data |\n| Data | Data | Data | Data | Data | Data |\n| Data | Data | Data | Data | Data | Data |",
        position: { x: 1756, y: 311 },
        title: "Message",
        output: { type: "null", id: "message_v5uoBbkLgj" },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 0,
            properties: {},
          },
        },
        size: { h: 369, w: 250 },
      },
      "aS-yMKvbMJ": {
        id: "aS-yMKvbMJ",
        type: "dumbotReactSnippet",
        user: true,
        content: "this is a better content!!!!!\n\nadding some more!",
        position: { x: 869, y: 457 },
        title: "React Component",
        properties: {
          label: "react snippet",
          code: 'function dumbot_react_customNode(React, ReactDOM, Grommet, Icons, _, UUID, StyledLibrary) {/* -- readonly -- */\nconst {useState,useEffect} = React;\nconst {Box, Button, Spinner} = Grommet;\nconst {nanoid} = UUID;\nconst styled = StyledLibrary.default;\nconst {Trash} = Icons;\n\n const ActionButton = styled(Button)`;\n     width: 40px;\n  background-color: ${(props) =>{\n\n    return props.theme.global.colors[props.bgColor || "botBubbleColor"]}};\n  border: ${(props) =>\n    !props.plain\n      ? `2px solid ${\n          props.theme.global.colors[props.fontColor || "botFontColor"]\n        }`\n      : "none"};\n  border-radius: 50%;\n  color: ${(props) =>\n    props.theme.global.colors[props.fontColor || "botFontColor"]};\n  svg {\n    fill: ${(props) =>\n      props.theme.global.colors[\n        props.active ? "botFocusColor" : props.fontColor || "botFontColor"\n      ]};\n    stroke: ${(props) =>\n      props.theme.global.colors[\n        props.active ? "botFocusColor" : props.fontColor || "botFontColor"\n      ]};\n  }\n\n  &: hover\n    ${(props) =>\n      props.disabled\n        ? undefined\n        : `\n  {\n    transform: scale(1.1);\n    transition: 0.3s ease-out;\n    box-shadow: ${\n      props.noOutline\n        ? "none"\n        : `0 0 2px 2px ${props.theme.global.colors["botFocusColor"]}`\n    };\n    color: ${props.theme.global.colors["botFocusColor"]};\n    opacity: 0.9;\n    svg {\n      fill: ${props.theme.global.colors["botFocusColor"]};\n      stroke: ${props.theme.global.colors["botFocusColor"]};\n    }\n  }\n  `};\n`;\n\nconst ChildComponent = (props) => {\nreturn(<Box  background="bars" pad="xlarge">\n{props.loading?<Spinner size="medium" color="red" /> : <Box>I\'m a child component</Box> }\n</Box>);\n}\n\nreturn function CustomUserComponent(nodeProps) { /* -- readonly -- */\n// lines in gray are readonly and you can\'t modify them.\n// the library imported are the ones yu can use for your component\n// this is just an example on what you can do\nconst [loading, setLoading] = useState(true);\nconst res = _.chunk([\'a\', \'b\', \'c\', \'d\'], 2);\nconst uuid = nanoid();\nuseEffect(() => {\n    if(loading) {\n        setTimeout(() => {\n            setLoading(false);\n        }, 1000);\n    }\n\n},[loading])\nconst onUserActioncall = () => {\n  nodeProps.onUserAction({test:123, res, uuid },nodeProps.ports.exit0);\n}\nreturn(<Box  background="brand" pad="xlarge">\n    {loading?<Spinner size="medium" /> : <Button  label="test remote prop" primary onClick={onUserActioncall} /> }\n     <ActionButton\n              icon={<Trash size="small" />}\n              onClick={onUserActioncall}\n              size="small"\n              bgColor="bars"\n              tip={nodeProps.variables.question1 || "test"}\n            />\n    <ChildComponent loading={loading}/>\n</Box>);\n}} /* -- readonly -- */\n',
        },
        output: { id: "cstComponent", type: "object" },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 1,
            properties: {},
          },
          exit1: {
            bgColor: "options",
            id: "exit1",
            text: "exit 1",
            index: 2,
            properties: { value: "exit 1" },
          },
          exit2: {
            bgColor: "options",
            id: "exit2",
            text: "exit 2",
            index: 3,
            properties: { value: "exit 2" },
          },
        },
        size: { h: 321, w: 250 },
      },
      heHGo4pKl2: {
        id: "heHGo4pKl2",
        type: "remoteFederatedNode",
        user: true,
        content: "Remote hosted federated module jj",
        position: { x: 819, y: 40 },
        title: "Remote federated module node",
        output: { type: "object", id: "remoteFederatedNode_EUD-PvSvVV" },
        properties: {
          label: "test",
          module: "./RemoteNodeExample",
          scope: "DumbotFederatedModulesScope",
          remoteUrl:
            "https://dumbot-federatednode-dt44z.ondigitalocean.app/remoteEntry.js",
          customProps: { childText: "pietro" },
        },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 1,
            properties: {},
          },
          exit1: {
            bgColor: "options",
            id: "exit1",
            text: "exit 1",
            index: 2,
            properties: { value: "exit 1" },
          },
          exit2: {
            bgColor: "options",
            id: "exit2",
            text: "exit 2",
            index: 3,
            properties: { value: "exit 2" },
          },
        },
        size: { h: 283, w: 250 },
      },
      "ZT-AyLLws-": {
        id: "ZT-AyLLws-",
        type: "tags",
        user: true,
        content: "You picked ${multiOut};\nCan you answer this now?? :smile:",
        position: { x: 478, y: 342 },
        title: "Question",
        output: { type: "color", id: "question_w4vefIRD64" },
        properties: {
          placeholder: "answer this...",
          type: "text",
          displayAs: "message",
          pattern: "123456",
          suggestions: ["www", "sdsdsd"],
          format: "dd/mm/yyyy-dd/mm/yyyy",
          validationMessage: "password should have !@#",
        },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 0,
            properties: {},
          },
        },
        size: { h: 237, w: 250 },
      },
      GRLFxkmKrV: {
        id: "GRLFxkmKrV",
        type: "humanTakeOver",
        user: true,
        content: "",
        position: { x: 472, y: 83 },
        title: "Human Take Over",
        output: { type: "array", id: "humanTakeOver_uHjlevFtNF" },
        properties: {
          label: "",
          displayAs: "footer",
          background: "transparent",
          hideInteractionLabel: true,
        },
        ports: {
          default: {
            bgColor: "brand",
            id: "default",
            text: "default",
            index: 0,
            properties: {},
          },
        },
        size: { h: 81, w: 250 },
      },
    },
    links: {
      pwS4h0oo_4r4qcwG_bGcl: {
        from: { nodeId: "node1", portId: "default" },
        id: "pwS4h0oo_4r4qcwG_bGcl",
        to: "KfB4u17Hzo",
        posTo: { x: 877, y: 198 },
      },
      Vk3ctMXwl4SE5JuSr_3hU: {
        from: { nodeId: "KfB4u17Hzo", portId: "option1" },
        id: "Vk3ctMXwl4SE5JuSr_3hU",
        to: "N2XbELZtyn",
        posTo: { x: 1171, y: 347 },
      },
      iWUL3nJcrBWcod7oTk7C2: {
        from: { nodeId: "KfB4u17Hzo", portId: "option2" },
        id: "iWUL3nJcrBWcod7oTk7C2",
        to: "N2XbELZtyn",
        posTo: { x: 1010, y: 469 },
      },
      Nj7uTXCVH9SvgbCoxgd9S: {
        from: { nodeId: "0Z3bTAzvaE", portId: "default" },
        id: "Nj7uTXCVH9SvgbCoxgd9S",
        to: "N2XbELZtyn",
        posTo: { x: 1446, y: 341 },
      },
      "2bVb-GYkjHnP66SxQl3a6": {
        from: { nodeId: "heHGo4pKl2", portId: "default" },
        id: "2bVb-GYkjHnP66SxQl3a6",
        to: "aS-yMKvbMJ",
        posTo: { x: 1073, y: 470 },
      },
      wRZyfhgzGozQgmzyiyjaF: {
        from: { nodeId: "aS-yMKvbMJ", portId: "default" },
        id: "wRZyfhgzGozQgmzyiyjaF",
        to: "0Z3bTAzvaE",
        posTo: { x: 1406, y: 291 },
      },
      vKTGdLUZGeFlHZeGF9GFk: {
        from: { nodeId: "aS-yMKvbMJ", portId: "exit2" },
        id: "vKTGdLUZGeFlHZeGF9GFk",
        to: "0Z3bTAzvaE",
        posTo: { x: 1378, y: 213 },
      },
      C84TMl49lDTKRYUy26mKP: {
        from: { nodeId: "aS-yMKvbMJ", portId: "exit1" },
        id: "C84TMl49lDTKRYUy26mKP",
        to: "N2XbELZtyn",
        posTo: { x: 1502, y: 594 },
      },
      "hdcS-D1ebNvRvURVnDoQq": {
        from: { nodeId: "ZT-AyLLws-", portId: "default" },
        id: "hdcS-D1ebNvRvURVnDoQq",
        to: "heHGo4pKl2",
        posTo: { x: 1205, y: 112 },
      },
      "Ftim-NJxh4jcycqVdqowL": {
        from: { nodeId: "KfB4u17Hzo", portId: "option5" },
        id: "Ftim-NJxh4jcycqVdqowL",
        to: "ZT-AyLLws-",
        posTo: { x: 530, y: 450 },
      },
      "fdZRC6bkmoWy7d6yog-lg": {
        from: { nodeId: "KfB4u17Hzo", portId: "option3" },
        id: "fdZRC6bkmoWy7d6yog-lg",
        to: "GRLFxkmKrV",
        posTo: { x: 504, y: 135 },
      },
      Mrqqs0abFwWk6lizAbvE3: {
        from: { nodeId: "GRLFxkmKrV", portId: "default" },
        id: "Mrqqs0abFwWk6lizAbvE3",
        to: "ZT-AyLLws-",
        posTo: { x: 627, y: 369 },
      },
      neZEE47Q3pgFWWq1gyd6U: {
        from: { nodeId: "0Z3bTAzvaE", portId: "exit2" },
        id: "neZEE47Q3pgFWWq1gyd6U",
        to: "Xe2ZftbxOG",
        posTo: { x: 1786, y: 361 },
      },
    },
    selected: {},
    paths: {
      "node1-default": "KfB4u17Hzo",
      "KfB4u17Hzo-option1": "N2XbELZtyn",
      "KfB4u17Hzo-option2": "N2XbELZtyn",
      "0Z3bTAzvaE-default": "N2XbELZtyn",
      "heHGo4pKl2-default": "aS-yMKvbMJ",
      "aS-yMKvbMJ-default": "0Z3bTAzvaE",
      "aS-yMKvbMJ-exit2": "0Z3bTAzvaE",
      "aS-yMKvbMJ-exit1": "N2XbELZtyn",
      "ZT-AyLLws--default": "heHGo4pKl2",
      "KfB4u17Hzo-option5": "ZT-AyLLws-",
      "KfB4u17Hzo-option3": "GRLFxkmKrV",
      "GRLFxkmKrV-default": "ZT-AyLLws-",
      "0Z3bTAzvaE-exit2": "Xe2ZftbxOG",
    },
  },
  name: "testupdt",
  botId: "SPFj05jqH34LaV5vzV4hh",
  userId: "auth0|6185b0f4c1db87006b5a2804",
  created: "2021-11-22T16:42:49.482Z",
  published: "2022-01-12T22:24:53.135Z",
};

//# A demo of React\n ${multiOut}   \n\nLift($L$) can be determined by Lift Coefficient ($C_L$) like the following\nequation.\n\n$$\nL = \\frac{1}{2} \\rho v^2 S C_L\n$$\n\nhttp://techslides.com/demos/sample-videos/small.webm\n\nWelcome *your* user with a nice **message**!😂\n      \n![image.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)<dumbot-boubble/>\nThese features **do not work by default**.\n        \n        \n👆 Use the toggle above to add the plugin.\n\n`react-markdown` is a markdown component for R ${multiOut} eact.\n\n👉 Changes are re-rendered as you type.\n\n👈 Try writing some markdown on the left.\n\n## Overview\n\n* Follows [CommonMark](https://commonmark.org)\n* Optionally follows [GitHub Flavored Markdown](https://github.github.com/gfm/)\n* Renders actual React elements instead of using `dangerouslySetInnerHTML`\n* Lets you define your own components (to render `MyHeading` instead of `h1`)\n* Has a lot of plugins\n\n## Table of contents\n\nHere is an example of a plugin in action\n([`remark-toc`](https://github.com/remarkjs/remark-toc)).\nThis section is replaced by an actual table of contents.\n\n## Syntax highlighting\n\nHere is an example of a plugin to highlight code:\n[`rehype-highlight`](https://github.com/rehypejs/rehype-highlight).\n\n```js\nimport React from 'react'\nimport ReactDOM from 'react-dom'\nimport ReactMarkdown from 'react-markdown'\nimport rehypeHighlight from 'rehype-highlight'\n\nReactDOM.render(\n  <ReactMarkdown rehypePlugins={[rehypeHighlight]}>{'# Your markdown here'}</ReactMarkdown>,\n  document.querySelector('#content')\n)\n```\n\nPretty neat, eh?\n\n## GitHub flavored markdown (GFM)\n\nFor GFM, you can *also* use a plugin:\n[`remark-gfm`](https://github.com/remarkjs/react-markdown#use).\nIt adds support for GitHub-specific extensions to the language:\ntables, strikethrough, tasklists, and literal URLs.\n\nThese features **do not work by default**.\n👆 Use the toggle above to add the plugin.\n\n| Feature    | Support              |\n| ---------: | :------------------- |\n| CommonMark | 100%                 |\n| GFM        | 100% w/ `remark-gfm` |\n\n~~strikethrough~~\n\n* [ ] task list\n* [x] checked item\n\nhttps://example.com\n\n## HTML in markdown\n\n⚠️ HTML in markdown is quite unsafe, but if you want to support it, you can\nuse [`rehype-raw`](https://github.com/rehypejs/rehype-raw).\nYou should probably combine it with\n[`rehype-sanitize`](https://github.com/rehypejs/rehype-sanitize).\n\n<blockquote>\n  👆 Use the toggle above to add the plugin.\n</blockquote>\n\n## Components\n\nYou can pass components to change things:\n\n```js\nimport React from 'react'\nimport ReactDOM from 'react-dom'\nimport ReactMarkdown from 'react-markdown'\nimport MyFancyRule from './components/my-fancy-rule.js'\n\nReactDOM.render(\n  <ReactMarkdown\n    components={{\n      // Use h2s instead of h1s\n      h1: 'h2',\n      // Use a component instead of hrs\n      hr: ({node, ...props}) => <MyFancyRule {...props} />\n    }}\n  >\n  </ReactMarkdown>,\n  document.querySelector('#content')\n)\n```\n\n## More info?\n\nMuch more info is available in the\n[readme on GitHub](https://github.com/remarkjs/react-markdown)!\n\n***\n\nA component by [Espen Hovlandsdal](https://espen.codes/)
