/* eslint-disable */
export const data = {
  nodes: {
    node1: {
      id: "node1",
      type: "start",
      user: false,
      title: "Start!",
      content:
        'Welcome *your* user with a nice **message**!😂\n<img src="//v2.grommet.io/assets/IMG_4245.jpg" alt="test" /><dumbot-boubble/>test part 2',
      position: { x: 22, y: 19 },
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
      },
      output: { id: "", type: "null" },
      size: { h: 366, w: 250 },
      updates: 3,
      properties: { externalVariables: ["test", "test2"] },
    },
    "9CRaFo_963xR4O9Pq_KoJ": {
      id: "9CRaFo_963xR4O9Pq_KoJ",
      type: "message",
      user: false,
      position: { x: 1253.333536783854, y: 119.91666158040363 },
      title: "Send a message",
      content: "here's your message",
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
      },
      output: { id: "", type: "null" },
      size: { h: 141, w: 250 },
      properties: {},
    },
    "8CrN_nPaQ1-nrN3ad93AO": {
      id: "8CrN_nPaQ1-nrN3ad93AO",
      type: "buttons",
      user: true,
      position: { x: 1318.666788736979, y: 381.54167175292963 },
      title: "Buttons 2",
      content: "please select your option",
      properties: {
        direction: "row",
        multiple: false,
        min: 2,
        max: 4,
        ports: {
          "X8FhFABftj3W-XrFy48H8": {
            text: "${test.names[0]}",
            value: "${test.names[0]}",
            icon: "Trash",
          },
          "SL2yv-5DeSXGBHiOvw5zM": {
            text: "${test.names[1]}",
            value: "${test.names[1]}",
            icon: "PlayFill",
          },
          O5UxVkBYJruM3IGhRScDn: {
            text: "${test.names[2]}",
            value: "${test.names[2]}",
            icon: "PlayFill",
          },
          answ1: {
            text: "multi4",
            value: "multi4",
            icon: "PlayFill",
          },
          answ2: {
            text: "multi5",
            value: "multi5",
            icon: "PlayFill",
          },
          default: {
            text: "(multi option exit)",
            value: "(multi option exit)",
          },
        },
      },
      output: { id: "btns2", type: "string" },
      ports: {
        "X8FhFABftj3W-XrFy48H8": {
          id: "X8FhFABftj3W-XrFy48H8",
          text: "${test.names[0]}",
          type: "option",
          properties: { value: "${test.names[0]}" },
          index: 6,
          selected: false,
        },
        "SL2yv-5DeSXGBHiOvw5zM": {
          id: "SL2yv-5DeSXGBHiOvw5zM",
          text: "${test.names[1]}",
          type: "option",
          properties: { value: "${test.names[1]}" },
          index: 5,
          selected: false,
        },
        O5UxVkBYJruM3IGhRScDn: {
          id: "O5UxVkBYJruM3IGhRScDn",
          text: "${test.names[2]}",
          type: "option",
          properties: { value: "${test.names[2]}" },
          index: 4,
          selected: false,
        },
        answ2: {
          id: "answ2",
          type: "option",
          text: "multi4",
          properties: { value: "multi4" },
          index: 3,
          selected: false,
        },
        answ1: {
          id: "answ1",
          type: "option",
          text: "multi5",
          properties: { value: "multi5" },
          index: 2,
          selected: false,
        },
        default: {
          id: "default",
          type: "default",
          text: "(multi option exit)",
          index: 1,
          selected: false,
        },
      },
      size: { h: 316, w: 250 },
      updates: 7,
    },
    "mWZIL8m-aSb-j7alzvE59": {
      id: "mWZIL8m-aSb-j7alzvE59",
      type: "message",
      output: { id: "", type: "null" },
      user: false,
      position: { x: 1745.9999847412107, y: 60.0000508626302 },
      title: "Send a message",
      content:
        "here's your summary:\nPick one is: ${aaa.data}\nAnswer q is: ${answerq}\nBtns 2 is: ${btns2}",
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
      },
      size: { h: 189, w: 250 },
      updates: 4,
      properties: {},
    },
    ZLX80zOfwAkkIE17i_HoF: {
      id: "ZLX80zOfwAkkIE17i_HoF",
      type: "question",
      user: true,
      position: { x: 913, y: 347.666748046875 },
      title: "Simple Question",
      content:
        "from second block ${2ndblock}?\n(from exit default)?\nuser choice: ${usrClikked}\nid:${cstmReactNode.id}\nname:${cstmReactNode.name}\nemail:${cstmReactNode.email}\n",
      output: { id: "answerq", type: "string" },
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
      },
      properties: {
        controlType: "input",
        type: "text",
        label: "text",
        value: "text",
        size: "medium",
        width: "medium",
        maxLength: 100,
        placeholder: "test placeholder",
        pattern: "",
        suggestions: ["test", "test2", "test3"],
        textAlign: "start",
      },
      size: { h: 261, w: 250 },
      updates: 7,
    },
    yW4YuAOtGTsfB3EW7N1al: {
      id: "yW4YuAOtGTsfB3EW7N1al",
      type: "question",
      user: true,
      position: { x: 915.3333129882812, y: 51.33331298828125 },
      title: "Simple Question",
      content:
        "can you answer this (from exit 1)?\nuser choice: ${usrClikked}\nid:${cstmReactNode.id}\nname:${cstmReactNode.name}\nemail:${cstmReactNode.email}\n",
      output: { id: "answerq", type: "string" },
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
      },
      properties: {
        controlType: "input",
        type: "text",
        label: "text",
        size: "medium",
        width: "medium",
        maxLength: 100,
        placeholder: "test placeholder",
        pattern: "",
        suggestions: ["test", "test2", "test3"],
        textAlign: "start",
      },
      size: { h: 237, w: 250 },
      updates: 6,
    },
    "GECvtsvImQKNoCcl_L-lR": {
      id: "GECvtsvImQKNoCcl_L-lR",
      type: "snippet",
      user: true,
      position: { x: 315.08341471354163, y: 73.25005849202473 },
      title: "Javascript ",
      content: "",
      output: { id: "", type: "null" },
      properties: {
        code: 'async function usersnippet(SnippetContext){\n  const callApi = async (label) => {\n    //onCallHost will call a function passed as a property into the bot instance if defined. You can cal an api\n    // from the host and provide data out\n    const data = await SnippetContext.onCallHost(label, SnippetContext.variables);\n    return data;\n  }\n\n  // you can use await \n  const res = await callApi("testlabel");\n  console.log("RESPONSEEEEE", res)\n  // set variables on the Bot\n  SnippetContext.onSetVariable("aaa", res);\n  // read variables from the bot\n  console.log("Available variables",SnippetContext.variables);\n  console.log("Available ports",SnippetContext.ports);\n  // proceed with the flow on port default\n  return SnippetContext.ports.exit1\n}',
      },
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
        exit1: {
          id: "exit1",
          type: "option",
          text: "exit 1",
          properties: { value: "exit 1" },
          index: 2,
        },
        exit2: {
          id: "exit2",
          type: "option",
          text: "exit 2",
          properties: { value: "exit 2" },
          index: 3,
        },
      },
      size: { h: 139, w: 250 },
      updates: 50,
    },
    "GsWp1nD07JeI8jtumwP-N": {
      id: "GsWp1nD07JeI8jtumwP-N",
      type: "custom",
      user: true,
      position: { x: 629, y: 81 },
      title: "Table",
      content:
        "Ask something to the user and create your custom React component to allow him to answer",
      properties: {
        code: "const {onSetVariable, onCallHost, onUserAction, theme} = NodeContext;\nreturn (props) => {\n    const [data, setData] = React.useState([]);\n    \n    const columns= [\n  {\n    property: 'name',\n    header: <Grommet.Text>Name with extra</Grommet.Text>,\n\n  },\n  {\n    property: 'email',\n    header: 'Email',\n  },\n  {\n    property: 'gender',\n    header: 'Gender',\n  },\n  {\n    property: 'status',\n    header: 'Status',\n  },\n];\nconst pinnedColumns = columns.map(c => ({ ...c }));\npinnedColumns[0].pin = true;\n    React.useEffect(() => {\n      const getData = async () => {\n        const res = await onCallHost();\n\n        setData(res? res.data : [] );\n      }\n     getData();\n    },[true]);\n    \n     React.useEffect(() => {\n       \n       console.log(\"rendering\")\n     },[true])\n\n    return (\n      <Grommet.Box background={theme.global.colors.bars} fill=\"vertical\">\n        <Grommet.DataTable\n        fill\n         pin\n         paginate\n         step={10}\n        background={{\n          pinned: { color: 'background-contrast' },\n        }}\n          columns={pinnedColumns}\n          data={data}\n          onClickRow={(event) => {\n            alert(event.datum.id);\n            let exit = NodeContext.ports.exit1;\n            if(event.datum.id < 2010){\n              onSetVariable(\"usrClikked\",\"less than 2010\");\n              exit = NodeContext.ports.default;\n            }else {\n              onSetVariable(\"usrClikked\",\"grater or equal than 2010\")\n            }\n            onUserAction(event.datum,exit)\n          \n          }}\n        />\n      </Grommet.Box>\n    )\n} //this line is readonly",
      },
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
        exit1: {
          type: "option",
          id: "exit1",
          text: "exit 1",
          index: 2,
        },
      },
      size: { h: 248, w: 250 },
      updates: 36,
      output: { id: "cstmReactNode", type: "object" },
    },
    lidyxkDjoLiPj7WqfGrXb: {
      id: "lidyxkDjoLiPj7WqfGrXb",
      type: "custom",
      user: true,
      position: { x: 447, y: 458 },
      title: "React Component",
      content: "Test File Upload",
      properties: {
        code: 'const {onSendAttachments, onUserAction, theme } = NodeContext;\nreturn (props) => { //this line is readonly\n    const [items, setItems] = React.useState([]);\n    const [loading, setLoading] = React.useState(false);\n    const Box = Grommet.Box;\n    const FileInput = Grommet.FileInput;\n    const DumbotIconButton = BotComponents.DumbotIconButton;\n    \n    const sendFiles = async () => {\n      let nodeOut = items;\n      try{\n        setLoading(true);\n        await onSendAttachments(items);\n      } catch(e) {\n        console.error(e);\n        nodeOut=e;\n      } finally {\n         setLoading(false);\n         onUserAction(nodeOut.toString(), NodeContext.ports.default);\n      }\n    }\n\n    return (\n      <Box align="center"  justify="start" pad="large">\n      <Box width="medium" background={theme.global.colors.bars} >\n        <FileInput\n          multiple={{\n            max: 5,\n          }}\n          onChange={(event, { files }) => {\n            console.log(event, files);\n            setItems(files);\n          }}\n        />\n      </Box>\n      <Box>\n       <DumbotIconButton\n        tip="Send files"\n        icon={loading ? <BotComponents.DumbotSpinner themeColor="accent-1" /> : <Icons.Play />}\n        onClick={sendFiles}\n        disabled={!items.length || loading}\n        bgColor="bars"\n        style={{ alignSelf: "center", padding: "8px", margin: "6px" }}\n      />     \n      </Box>\n    </Box>\n    )\n} //this line is readonly',
      },
      ports: {
        default: {
          id: "default",
          type: "default",
          text: "output",
          index: 1,
        },
      },
      size: { h: 141, w: 250 },
      output: { id: "files", type: "object" },
      updates: 18,
    },
  },
  links: {
    "DpM7iUW4B--mezk_Yg7_-": {
      from: { nodeId: "8CrN_nPaQ1-nrN3ad93AO", portId: "default" },
      id: "DpM7iUW4B--mezk_Yg7_-",
      to: "mWZIL8m-aSb-j7alzvE59",
      posTo: { x: 2006.6666666666663, y: 369.99999999999994 },
    },
    U0oMZKpFigOwJQGBOKeoJ: {
      from: { nodeId: "9CRaFo_963xR4O9Pq_KoJ", portId: "default" },
      id: "U0oMZKpFigOwJQGBOKeoJ",
      to: "8CrN_nPaQ1-nrN3ad93AO",
      posTo: { x: 1594.9999999999998, y: 324.99999999999994 },
    },
    uhehmg5nNYK5sO4GTjG1K: {
      from: { nodeId: "ZLX80zOfwAkkIE17i_HoF", portId: "default" },
      id: "uhehmg5nNYK5sO4GTjG1K",
      to: "9CRaFo_963xR4O9Pq_KoJ",
      posTo: { x: 1314.9999999999998, y: 311.66666666666663 },
    },
    B_STvIfAoufmQQ81Azt3E: {
      from: { nodeId: "yW4YuAOtGTsfB3EW7N1al", portId: "default" },
      id: "B_STvIfAoufmQQ81Azt3E",
      to: "9CRaFo_963xR4O9Pq_KoJ",
      posTo: { x: 1333.333333333333, y: 283.3333333333333 },
    },
    qIbK5lBpcFX1NwqDyhRXY: {
      from: { nodeId: "GsWp1nD07JeI8jtumwP-N", portId: "exit1" },
      id: "qIbK5lBpcFX1NwqDyhRXY",
      to: "yW4YuAOtGTsfB3EW7N1al",
      posTo: { x: 1013, y: 626 },
    },
    hkVNMbvoUBYNBiAXE3MuX: {
      from: { nodeId: "GsWp1nD07JeI8jtumwP-N", portId: "default" },
      id: "hkVNMbvoUBYNBiAXE3MuX",
      to: "lidyxkDjoLiPj7WqfGrXb",
      posTo: { x: 568, y: 384 },
    },
    "4jQa2OnC13rMO0fXR9lZc": {
      from: { nodeId: "lidyxkDjoLiPj7WqfGrXb", portId: "default" },
      id: "4jQa2OnC13rMO0fXR9lZc",
      to: "ZLX80zOfwAkkIE17i_HoF",
      posTo: { x: 975, y: 432 },
    },
    Wfrmx9oE9q5A6OZNItBgE: {
      from: { nodeId: "node1", portId: "default" },
      id: "Wfrmx9oE9q5A6OZNItBgE",
      to: "GECvtsvImQKNoCcl_L-lR",
      posTo: { x: 375, y: 185 },
    },
    bse_d0lg_OhPuV9csoQ6u: {
      from: { nodeId: "GECvtsvImQKNoCcl_L-lR", portId: "exit1" },
      id: "bse_d0lg_OhPuV9csoQ6u",
      to: "GsWp1nD07JeI8jtumwP-N",
      posTo: { x: 696, y: 197 },
    },
  },
  selected: {
    node1: false,
    "9CRaFo_963xR4O9Pq_KoJ": false,
    "8CrN_nPaQ1-nrN3ad93AO": false,
    "mWZIL8m-aSb-j7alzvE59": false,
    ZLX80zOfwAkkIE17i_HoF: false,
    yW4YuAOtGTsfB3EW7N1al: false,
    "GECvtsvImQKNoCcl_L-lR": false,
    "GsWp1nD07JeI8jtumwP-N": false,
    lidyxkDjoLiPj7WqfGrXb: false,
  },
};
